export const jobs = [
	{
		position: "Position1",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: false,
		isProposal: true,
		category: "Category",
		skills: [1, 2, 3],
		hourRate: "Hour Rate",
	},
	{
		position: "Position2",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: false,
		category: "Category",
		skills: [1, 2, 3],
		hourRate: "Hour Rate",
	},
	{
		position: "Position3",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: true,
		category: "Category",
		skills: [1, 2, 3],
		hourRate: "Hour Rate",
	},
	{
		position: "Position4",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: false,
		isProposal: true,
		category: "Category",
		skills: [1, 2, 3],
		hourRate: "Hour Rate",
	},
	{
		position: "Position5",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: false,
		category: "Category",
		skills: [1, 2, 3],
		hourRate: "Hour Rate",
	},
	{
		position: "Position6",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: true,
		category: "Category",
		skills: [1, 2, 3],
		hourRate: "Hour Rate",
	},
	{
		position: "Position7",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: true,
		category: "Category",
		skills: [1, 2, 3],
		hourRate: "Hour Rate",
	},
	{
		position: "Position8",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: false,
		isProposal: true,
		category: "Category",
		skills: [1, 2, 3],
		hourRate: "Hour Rate",
	},
	{
		position: "Position9",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: true,
		category: "Category",
		skills: [1, 2, 3],
		hourRate: "Hour Rate",
	},
	{
		position: "Position10",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: true,
		category: "Category",
		skills: [1, 2, 3],
		hourRate: "Hour Rate",
	},
];
