export const jobs = [
	{
		position: "Position",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: true,
	},
	{
		position: "Position",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: false,
	},
	{
		position: "Position",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: true,
	},
	{
		position: "Position",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: true,
	},
	{
		position: "Position",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: false,
	},
	{
		position: "Position",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: true,
	},
	{
		position: "Position",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: true,
	},
	{
		position: "Position",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: true,
	},
	{
		position: "Position",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: true,
	},
	{
		position: "Position",
		location: "Location",
		employmentType: "Employment type",
		availableAmountOfHours: "Hour amount",
		workExperience: "Work experience",
		levelEnglish: "English level",
		date: "date",
		isPublished: true,
		isProposal: true,
	},
];
